config/routes.rb
Rails.application.routes.draw do
  resources :goals
  root 'home#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :new, :create] do
    resources :transactions, only: [:index, :show, :edit, :update]
    resources :accounts
    resources :budgets, except: [:index]
    resources :goals
  end
  
  # Clean up on these next... 
  post '/users/piechart', to: 'users#piechart'
  post '/users/linegraph', to: 'users#linegraph'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  post 'graph/data', to: 'graph#data'

  get '/users/data', :defaults => { :format => 'json' }

end

# Cleaned
  # get '/update/:id', to: 'users#edit', as: 'edit'
  # patch '/update/:id', to: 'users#update', as: 'user_update'
  # post 'accounts/create', to: 'accounts#create'
  # patch '/update_accounts', to: 'plaidapi#update_accounts'

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password
  validates_presence_of :password_confirmation
  validates :password, length: { minimum: 8 }, allow_nil: true

  validates :email, uniqueness: true
  validates_format_of :email,:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_presence_of :first_name
  validates_presence_of :last_name

  has_many :public_tokens
  has_many :accounts
  has_many :transactions, through: :accounts
  has_many :categories, through: :transactions
  has_many :budgets
  has_many :goals

  def total_debt
    if accounts.nil?
      ""
    else
      debt = 0.00
      accounts.each do |a|
        if a.acct_type == "credit"
          debt += a.current_balance
        end
      end
      return debt
    end
  end

  def total_cash
    if accounts.nil?
      ""
    else
      cash = 0.00
      accounts.each do |a|
        if a.acct_type == "depository"
          cash += a.current_balance
        end
      end
      return cash
    end
  end

  def weekly_budget
    if transactions.nil?
      ""
    else
      transactions.where(date: Date.today.beginning_of_week..Date.today.end_of_week).sum(:amount)
    end
  end

  def monthly_budget
    if transactions.nil?
      ""
    else
      transactions.where(date: Date.today.beginning_of_month..Date.today.end_of_month).sum(:amount)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy, :data]
skip_before_action :verify_authenticity_token, only: [:linegraph, :piechart]

  def new
    @user = User.new
  end
  
  def show
  end

  def create
    @user = User.new(user_params)
        if !@user.save
          flash[:errors] = []
          flash[:message] = "Please fix the following errors:"
          @user.errors.each do |k,v|
              flash[:errors] << "#{k}: #{v}"
          end
          render :new
        else
           session[:user_id] = @user.id
           redirect_to user_path(@user)
        end
  end


  def edit
  end

  def update
    @user = User.find(session[:user_id])
    if !@user.update(user_params)
          flash[:errors] = []
          flash[:message] = "Please fix the following errors:"
          @user.errors.each do |k,v|
              flash[:errors] << "#{k}: #{v}"
          end
          render :edit
        else
            redirect_to @user
        end
  end

  def piechart
    @month = params[:month].to_i
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.js
    end
  end

  def linegraph
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.js
    end
  end

  def data
    respond_to do |format|
      format.json {
        render :json
      }
    end
  end

  private
  
  def set_user
    @user = User.find(session[:user_id])
  end

  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def id_format(string)
    newstring = string.sub(' & ','-')
    return newstring.downcase.sub(' ','-')
  end

  def display_amount(month, key)
    x = month[month.keys.first][key]
    !x.nil? ? number_to_currency(x, {precision: 0, negative_format: "(%u%n)"}) : "$0"
  end

  def display(value)
    !value.nil? ? number_to_currency(value, {precision: 0, negative_format: "(%u%n)"}) : "$0"
  end
end

app/views/users/_income_statement_divs.html.erb
<div id="main-table-area">
  <div id="main-table">

    <% if !@user.accounts.empty? %>

    <div class="table">

      <div class="tHead">
        <div class="tRow">
          <div class="tCell tHeader row-label"></div>
        <% income_statement = IncomeStatement.new(@user, :month, Date.new(2015, 4, 1), Date.new(2016, 3, 1)) %>

          <% income_statement.time_period.each do |period| %>
            <% if income_statement.increment == :month %>
              <div class="tCell tHeader month"><%= Date.strptime(period.month.slice(0..1),'%m').strftime('%b') %></div>
            <% elsif income_statement.increment == :day %>
              <div class="tCell tHeader day"><%= period.date.strftime('%a') %></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="tBody">

        <% table_hash = income_statement.generate_table_hash %>
        
        <% table_hash.each do |root_cat, line_item| %>

          <% line_item.each do |line_item, subcat| %>
            <% if !subcat.kind_of?(Array) %>
                  
              <% subcat.each do |subcat, leaves| %>
                <% if !leaves.kind_of?(Array) %> <!-- if subcat = total food -->
                  <% leaves.each do |subfood, values| %>
                    <div class="tRow expenses leaves food" id="<%= id_format(subfood) %>">
                      <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <%= subfood %></div>
                      <% values.each do |period| %>
                        <div class="tCell"><%= display(period) %></div>
                      <% end %>
                    </div>

                  <% end %>

                  <div class="tRow <%= id_format(root_cat) %> child <%= id_format(line_item) %>" id="<%= id_format(subcat) %>" >
                    <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp <%= subcat %></div>
                      <% income_statement.parent_sum(table_hash[root_cat][line_item][subcat]).each do |period| %>
                        <div class="tCell"><%= display(period) %></div>
                      <% end %>
                  </div>

                <% else %> <!-- if subcat ie shopping or most categories -->
                  
                  <div class="tRow <%= id_format(root_cat) %> child <%= id_format(line_item) %>" id="<%= id_format(subcat) %>" >
                    <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp <%= subcat %></div>
                      <% leaves.each do |period| %>
                        <div class="tCell"><%= display(period) %></div>
                      <% end %>
                  </div>


                <% end %>

              <% end %>
              <div class="tRow <%= id_format(root_cat) %> subcategory" id="<%= id_format(line_item) %>">
                <div class="tCell row-label">&nbsp&nbsp <%= line_item %></div>
                <% income_statement.parent_sum(table_hash[root_cat][line_item]).each do |period| %>
                  <div class="tCell"><%= display(period) %></div>
                <% end %>
              </div>

            <% else %> <!-- if subcat = array so line_item = something like Bonus -->
              
              <div class="tRow <%= id_format(root_cat) %> subcategory" id="<%= id_format(line_item) %>">
                <div class="tCell row-label">&nbsp&nbsp <%= line_item %></div>
                <% subcat.each do |period| %>
                  <div class="tCell"><%= display(period) %></div>
                <% end %>
              </div>

            <% end %>
          <% end %>

          <div class="tRow root <%=id_format(root_cat)%>">
            <div class="tCell row-label">Total <%= root_cat %></div>
              <% income_statement.parent_sum(table_hash[root_cat]).each do |period| %>
                <div class="tCell"><%= display(period) %></div>
              <% end %>
          </div>
        <% end %>


        <div class="tRow root net">
          <div class="tCell row-label">Net Savings</div>
          <% income_statement.generate_net(table_hash).each do |m| %>
            <div class="tCell"><%= display(m) %></div>
          <% end %>
        </div>

      </div class="tbody">
    </div>




    <% else %>
    <p>Please add an account using the link above.</p>
    <% end %>

  </div>
</div>

<script>
    $(document).ready(function(){
        $.ajax ({
             url: '/users/linegraph',
             method: 'post',
             data: {
              'increment': "<%= income_statement.increment.to_s %>",
              'start_date': "<%= income_statement.start_date.to_s %>",
              'end_date': "<%= income_statement.end_date.to_s %>"
             }
           }).done(console.log("done"))
    })
  </script>

app/views/users/edit.html.erb
    <div id="container">

            <%= render template: "layouts/_header" %>
            <%= render template: "layouts/_sidebar" %>

            <!--main content start-->
            <section class="main-content-wrapper">
            <section id="main-content">

            <%= render template: "layouts/_tiles_top" %>

                <!--dashboard charts and income statementstart-->
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div>

                            <h2> Hi <%= @user.first_name %> <%= @user.last_name %>!</h2>
                            <br>
                            <h4>Here is your current information. Feel free to edit as necessary:</h4>
                            <br>
                            </div>

                            <font color="red"><% if flash[:errors] %>
                            <h5><%= flash[:message] %>
                            <% flash[:errors].each do |error| %>
                            <li><%= error %></li>
                            <% end %>
                            <% end %>

                            <%= form_for @user do |f| %>

                            <div class="form-group">
                              <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
                            </div>

                             <div class="form-group">
                              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
                            </div>

                            <div class="form-group">
                              <%= f.email_field :email, class: 'form-control', placeholder: 'Enter your email' %>
                            </div>
                             <div class="form-group">
                             <%= f.password_field :password, class: 'form-control', placeholder: "New Password"%>
                            </div>
                              <div class="form-group">
                                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Retype your new password"%><br>
                            </div>

                            <%= f.submit "Edit", class: "btn btn-primary" %>
                            <% end %>

                        </div>
                    </div>

                </div>

        </section>
        </section>
    </div>

app/views/users/incomestatement.js.erb
// alert("start")
<% income_statement = IncomeStatement.new(@user, @increment, @start_date, @end_date) %>

$('div.table').html('<div class="tHead">\
        <div class="tRow">\
          <div class="tCell tHeader row-label"></div>\
\
          <% income_statement.time_period.each do |period| %>\
            <% if income_statement.increment == :month %>\
              <div class="tCell tHeader month"><%= Date.strptime(period.month.slice(0..1),'%m').strftime('%b') %></div>\
            <% elsif income_statement.increment == :day %>\
              <div class="tCell tHeader day"><%= period.date.strftime('%a') %></div>\
            <% end %>\
          <% end %>\
        </div>\
      </div>\
      <div class="tBody">\
\
        <% table_hash = income_statement.generate_table_hash %>\
\
        <% table_hash.each do |root_cat, line_item| %>\
\
          <% line_item.each do |line_item, subcat| %>\
            <% if !subcat.kind_of?(Array) %>\
\
              <% subcat.each do |subcat, leaves| %>\
                <% if !leaves.kind_of?(Array) %> <!-- if subcat = total food -->\
                  <% leaves.each do |subfood, values| %>\
                    <div class="tRow expenses leaves food" id="<%= id_format(subfood) %>">\
                      <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <%= subfood %></div>\
                      <% values.each do |period| %>\
                        <div class="tCell"><%= display(period) %></div>\
                      <% end %>\
                    </div>\
\
                  <% end %>\
\
                  <div class="tRow <%= id_format(root_cat) %> child <%= id_format(line_item) %>" id="<%= id_format(subcat) %>" >\
                    <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp <%= subcat %></div>\
                      <% income_statement.parent_sum(table_hash[root_cat][line_item][subcat]).each do |period| %>\
                        <div class="tCell"><%= display(period) %></div>\
                      <% end %>\
                  </div>\
\
                <% else %> <!-- if subcat ie shopping or most categories -->\
                  \
                  <div class="tRow <%= id_format(root_cat) %> child <%= id_format(line_item) %>" id="<%= id_format(subcat) %>" >\
                    <div class="tCell row-label">&nbsp&nbsp&nbsp&nbsp <%= subcat %></div>\
                      <% leaves.each do |period| %>\
                        <div class="tCell"><%= display(period) %></div>\
                      <% end %>\
                  </div>\
\
\
                <% end %>\
\
              <% end %>\
              <div class="tRow <%= id_format(root_cat) %> subcategory" id="<%= id_format(line_item) %>">\
                <div class="tCell row-label">&nbsp&nbsp <%= line_item %></div>\
                <% income_statement.parent_sum(table_hash[root_cat][line_item]).each do |period| %>\
                  <div class="tCell"><%= display(period) %></div>\
                <% end %>\
              </div>\
\
            <% else %> <!-- if subcat = array so line_item = something like Bonus -->\
              \
              <div class="tRow <%= id_format(root_cat) %> subcategory" id="<%= id_format(line_item) %>">\
                <div class="tCell row-label">&nbsp&nbsp <%= line_item %></div>\
                <% subcat.each do |period| %>\
                  <div class="tCell"><%= display(period) %></div>\
                <% end %>\
              </div>\
\
            <% end %>\
          <% end %>\
\
          <div class="tRow root <%=id_format(root_cat)%>">\
            <div class="tCell row-label">Total <%= root_cat %></div>\
              <% income_statement.parent_sum(table_hash[root_cat]).each do |period| %>\
                <div class="tCell"><%= display(period) %></div>\
              <% end %>\
          </div>\
        <% end %>\
\
\
        <div class="tRow root net">\
          <div class="tCell row-label">Net Savings</div>\
          <% income_statement.generate_net(table_hash).each do |m| %>\
            <div class="tCell"><%= display(m) %></div>\
          <% end %>\
        </div>\
\
      </div class="tbody">')

$(function(){
  hideYoKids()
  showSubcategories()
})

app/views/users/linegraph.js.erb
// alert("start")
var data = []
var format = d3.time.format("%Y-%m")
var abbrevMonthFormat = d3.time.format("%b")

<% ytd_data = IncomeStatement.year_to_date(@user.id) %>
<% budget_data = IncomeStatement.budget(@user.id) %>
<% ltm_data = IncomeStatement.last_twelve_months(@user.id) %>

<% table_data = ytd_data.values.first + budget_data.values.first %>
<% table_data.each_with_index do |hash, idx| %>
  var line_hash = {}
  <% hash_obj = OpenStruct.new(hash[idx + 1]) %>
  line_hash["date"] = format.parse("2016-<%= idx + 1 %>")
  line_hash["exp"] = Math.abs(<%= hash_obj.Expenses %>)
  line_hash["inc"] = <%= hash_obj.Income %>
  data.push(line_hash)
<% end %>


$(function() {
  var margin = {top: 20, right: 20, bottom: 30, left: 60},
      width = $('#line-graph').width() - margin.left - margin.right,
      height = 360 - margin.top - margin.bottom;

  function make_x_axis() {
    return d3.svg.axis()
        .scale(x)
        .orient('bottom')
        .ticks(data.length)
  }

  function make_y_axis() {
    return d3.svg.axis()
        .scale(y)
        .orient('left')
        .ticks(data.length)
  }

  var x = d3.time.scale()
      .range([0, width]);

  var y = d3.scale.linear()
      .range([height, 0]);

  var xAxis = d3.svg.axis()
      .scale(x)
      .ticks(data.length)
      .tickFormat(function(d, i){
        return abbrevMonthFormat(d)})
      .orient("bottom");

  var yAxis = d3.svg.axis()
      .scale(y)
      .orient("left");

  var expLine = d3.svg.line()
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.exp); });

  var incLine = d3.svg.line()
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.inc); });

  var svg = d3.select("#line-graph").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
      .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    x.domain(d3.extent(data, function(d) { return d.date; }));
    y.domain([
      d3.min(data, function(d) {
        if (d.inc < d.exp){return d.inc - (.2*d.inc)} else {return d.exp - (.2*d.exp)}
      }),
      d3.max(data, function(d) {
        if (d.inc > d.exp){return d.inc + (.2*d.inc)} else {return d.exp + (.2*d.exp)}
      })
    ]);

    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
        .append("text");

    svg.append('g')
        .attr('class', 'grid')
        .call(make_y_axis()
          .tickSize(-width,0,0)
          .tickFormat(""))

    svg.append("path")
        .data([data])
        .attr("class", "incomeLine")
        .attr("d", incLine);

    svg.append("path")
        .datum(data)
        .attr("class", "expenseLine")
        .attr("d", expLine);
      
})

app/views/users/new.html.erb
    <section id="login-container">

        <div class="row">
            <div class="col-md-3" id="login-wrapper">
                <div class="panel panel-primary animated flipInY">
                    <center><h1>Welcome to Benjamin!</h1></center><br>

                    <div class="panel-heading">


                          <h3 class="panel-title">
                           Sign Up
                        </h3>
                    </div>
                    <div class="panel-body">
                        <p >Already a member? <strong><%= link_to "Sign In", login_path %></strong></p>
                          <font color="red"><% if flash[:errors] %>
                          <h5><%= flash[:message] %>
                            <% flash[:errors].each do |error| %>
                            <li><%= error %></li>
                            <% end %>
                        <% end %>
                          <br>

                          <%= form_for @user, url: '/signup' do |f| %>



                            <div class="form-group">
                              <%= f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
                            </div>

                             <div class="form-group">
                              <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
                            </div>

                            <div class="form-group">
                              <%= f.email_field :email, class: 'form-control', placeholder: 'Enter your email' %>
                            </div>
                             <div class="form-group">
                             <%= f.password_field :password, class: 'form-control', placeholder: "Password"%>
                            </div>
                              <div class="form-group">
                                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Retype your password"%><br>
                            </div>

                          <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
                        <% end %>

                    </div>
                </div>
            </div>
        </div>

    </section>

app/views/users/piechart.js.erb
<% ytd_data = IncomeStatement.year_to_date(@user.id) %>
<% budget_data = IncomeStatement.budget(@user.id) %>
<% ltm_data = IncomeStatement.last_twelve_months(@user.id) %>

<% table_data = ytd_data.values.first + budget_data.values.first %>
<% month_data = table_data[@month - 1][@month] %>

var dataset = []
console.log(dataset)
dataset[0] = {}; dataset[1] = {}; dataset[2] = {}; dataset[3] = {}; dataset[4] = {}; dataset[5] = {}
dataset[0]["label"] = "Fixed & Recurring"; dataset[0]["count"] = Math.abs(<%= month_data["Fixed & Recurring"]%>)
dataset[1]["label"] = "Variable"; dataset[1]["count"] = Math.abs(<%= month_data["Variable"]%>)
dataset[2]["label"] = "Discretionary"; dataset[2]["count"] = Math.abs(<%= month_data["Discretionary"]%>)
dataset[3]["label"] = "Life"; dataset[3]["count"] = Math.abs(<%= month_data["Life"]%>)
dataset[4]["label"] = "Other"; dataset[4]["count"] = Math.abs(<%= month_data["Other"]%>)
dataset[5]["label"] = "Uncategorized"; dataset[5]["count"] = Math.abs(<%= month_data["Special"]%>)
console.log(dataset)

$.each(dataset, function(index,value) {
  if (isNaN(value["count"])) {
    value["count"] = 0;
  }
})

var test = d3.select('svg#pie-chart-svg').selectAll('g')
if (test[0].length == 0) {
  var width = 360;
  var height = 360;
  var radius = Math.min(width*.8, height*.8) / 2;

  var color = d3.scale.category20c();

  var svg = d3.select('svg#pie-chart-svg')
    .attr('width', width)
    .attr('height', height)
    .append('g')
    .attr('transform', 'translate(' + (width / 2) + ',' + (height / 2) + ')');

  var arc = d3.svg.arc()
  .outerRadius(radius);

  var pie = d3.layout.pie()
    .value(function(d) {return d.count;})
    .sort(null);

  var path = svg.selectAll('path')
    .data(pie(dataset))
    .enter()
    .append('path')
    .attr('d', arc)
    .attr('fill', function(d, i) { 
      return color(d.data.label);
    })
    .each(function(d) { this._current = d});
} else {
  console.log("semi-working?")
  var path2 = d3.select('svg#pie-chart-svg')
    .selectAll('path')
    .data(pie(dataset));
  path2.transition()
    .duration(750)
    .attrTween('d', function(d) {
      var interpolate = d3.interpolate(this._current, d);
      this._current = interpolate(0);
      return function(t) {
        return arc(interpolate(t));
      };
    });
    }

app/views/users/show.html.erb
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Benjamin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <style>
    .incomeLine {
      fill:none;
      stroke: #31a354;
      stroke-width:3px;
    }
    .expenseLine {
      fill:none;
      stroke: #e6550d;
      stroke-width:3px;
    }

    path.domain {
      fill:none;
      stroke:#333;
      stroke-width:0.5px;
    }

    .grid .tick {
      stroke: #777;
      stroke-dasharray: 3,3;
      stroke-width:0.25px;
    }
    .grid path {
      stroke-width: 0;
    }
    #piechartkey {
      width:150px;
      display:inline;
      position:absolute;
      top:150px;
    }
    #pie-chart-svg {
      display:inline;
    }
    </style>
</head>

<body class="off-canvas">
    <div id="container">

            <%= render template: "layouts/_header" %>

            <%= render template: "layouts/_sidebar" %>

            <!--main content start-->
            <section class="main-content-wrapper">
            <section id="main-content">

            <%= render template: "layouts/_tiles_top" %>

                <!--charts space start -->
                <div class="row">
                    <div class="col-md-7" >
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h2 class="panel-title">Income & Spending</h2>
                                <div class="actions pull-right">
                                    <i class="fa fa-chevron-down"></i>
                                    <i class="fa fa-times"></i>
                                </div>
                            </div>
                           <div id="line-graph"></div>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h2 class="panel-title">Spending by Category</h2>
                                <div class="actions pull-right">
                                    <i class="fa fa-chevron-down"></i>
                                    <i class="fa fa-times"></i>
                                </div>
                            </div>
                            <div id="pie-chart">
                                <svg id="pie-chart-svg"></svg>
                                <%= image_tag "piechartkey.png", id: 'piechartkey' %>
                            </div>
                        </div>
                    </div>
                </div>
                <!--charts end -->

                <!--dashboard charts and income statement start-->
                <div class="row">
                <div class="col-md-12">

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="btn btn-primary btn-trans">
                                <%= link_to "Update All Accounts", user_account_path(@user, @user.accounts), method: "patch" %>
                            </div>
                                <%= render "income_statement_divs" %>

            <!-- Modal start -->
            <div>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#budetModel">
                + Add a budget
                </button>

                <!-- Modal -->
                  <div class="modal fade" id="budetModel" tabindex="-1" role="dialog" aria-labelledby="budetModelLabel">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-budget" id="add-budget">Budget</h4>
                            <p>Add a monthly budget amount and select a category</p>
                        </div>
                        <div class="modal-body">
                            <%= form_for [@user, Budget.new] do |f| %>
                            <%= f.label :amount %>
                            <%= f.text_field :amount, placeholder: '$0' %>

                            <%= f.label :category %>
                            <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true %>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <%= f.submit "Save Budget", class: 'btn btn-success' %>
                            <% end %>
                        </div>
                        </div>
                    </div>
                    </div>
            </div>
                        </div>
                    </div>
                </div>
                </div>

            </section>
        </section>
    </div>
    <!--main content end-->

    <!--Global JS-->
    <!-- <script src="assets/js/jquery-1.10.2.min.js"></script>
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/application.js"></script>
    <script src="assets/plugins/navgoco/jquery.navgoco.min.js"></script>
    <script src="assets/plugins/waypoints/waypoints.min.js"></script> -->

    <!--Page Level JS-->
    <!-- <script src="assets/plugins/countTo/jquery.countTo.js"></script>
     -->
    <script type="javascript" src="income_statement.js"></script>
    <script>
    $(function(){
        $.ajax ({
             url: '/users/linegraph',
             method: 'post'
           }).done(console.log("done"))
        $.ajax ({
             url: '/users/piechart',
             method: 'post',
             data: { 'month' : <%= Date.today.month %> },
           })
    })
    </script>
</body>

</html>