config/routes.rb
Rails.application.routes.draw do
  resources :goals
  root 'home#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :new, :create] do
    resources :transactions, only: [:index, :show, :edit, :update]
    resources :accounts
    resources :budgets, except: [:index]
    resources :goals
  end
  
  # Clean up on these next... 
  post '/users/piechart', to: 'users#piechart'
  post '/users/linegraph', to: 'users#linegraph'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  post 'graph/data', to: 'graph#data'

  get '/users/data', :defaults => { :format => 'json' }

end

# Cleaned
  # get '/update/:id', to: 'users#edit', as: 'edit'
  # patch '/update/:id', to: 'users#update', as: 'user_update'
  # post 'accounts/create', to: 'accounts#create'
  # patch '/update_accounts', to: 'plaidapi#update_accounts'

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :require_login, only: [:index]

  def index
  end

end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <style>
    #mainlogo {
      width: 350px
    }
  </style>


    <div class="text-center">
      <br><br><br><br><br>

      <%= image_tag 'Benjamin-Logo-no-pad.png', id: "mainlogo" %>
      <h4><i>It's all about the Benjamins</h4><br>

      <%= link_to "Sign up", signup_path, class: "btn2 btn-primary" %><br><br><br>
      <%= link_to "Log in", login_path, class: "btn2 btn-primary" %><br>

    </div>


</body>
</html>