config/routes.rb
Rails.application.routes.draw do
  resources :goals
  root 'home#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :new, :create] do
    resources :transactions, only: [:index, :show, :edit, :update]
    resources :accounts
    resources :budgets, except: [:index]
    resources :goals
  end
  
  # Clean up on these next... 
  post '/users/piechart', to: 'users#piechart'
  post '/users/linegraph', to: 'users#linegraph'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  post 'graph/data', to: 'graph#data'

  get '/users/data', :defaults => { :format => 'json' }

end

# Cleaned
  # get '/update/:id', to: 'users#edit', as: 'edit'
  # patch '/update/:id', to: 'users#update', as: 'user_update'
  # post 'accounts/create', to: 'accounts#create'
  # patch '/update_accounts', to: 'plaidapi#update_accounts'

app/controllers/graph_controller.rb
class GraphController < ApplicationController
  def index
  end

  def data
    @user = User.find(session[:user_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/views/graph/data.js.erb
var data = []

<% table_data = IncomeStatement.monthly_by_year_view(@user.id, 2014) %>
<% table_data.each_with_index do |hash, idx| %>
  var line_hash = {}
  <% hash_obj = OpenStruct.new(hash[idx + 1]) %>
  line_hash["date"] = <%= idx + 1 %>
  line_hash["exp"] = <%= hash_obj.Expenses %>
  line_hash["inc"] = <%= hash_obj.Income %>
  data.push(line_hash)
<% end %>


$(function() {
  var margin = {top: 20, right: 20, bottom: 30, left: 50},
      width = 720 - margin.left - margin.right,
      height = 400 - margin.top - margin.bottom;

  var x = d3.scale.linear()
      .range([0, width]);

  var y = d3.scale.linear()
      .range([height, 0]);

  var xAxis = d3.svg.axis()
      .scale(x)
      .orient("bottom");

  var yAxis = d3.svg.axis()
      .scale(y)
      .orient("left");

  var expLine = d3.svg.line()
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.exp); });

  var incLine = d3.svg.line()
      .x(function(d) { return x(d.date); })
      .y(function(d) { return y(d.inc); });

var svg = d3.select("#chart").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    x.domain(d3.extent(data, function(d) { return d.date; }));
    y.domain([
      d3.min(data, function(d) {
        if (d.inc < d.exp){return d.inc} else {return d.exp}
    }),
      d3.max(data, function(d) {
        if (d.inc > d.exp){return d.inc} else {return d.exp}
    })]);


    svg.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis);

    svg.append("g")
        .attr("class", "y axis")
        .call(yAxis)
      .append("text")
        // .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .attr("dx", 20)
        // .style("text-anchor", "end")
        .text("Dollars ($)");

    svg.append("path")
        .data([data])
        .attr("class", "line1")
        .attr("d", incLine);

    svg.append("path")
        .datum(data)
        .attr("class", "line2")
        .attr("d", expLine);

})

app/views/graph/donut.js.erb
var data = []


<%  donut_data = [ %>
<%	{"label":"Discretionary", "color":"#3366CC", "value": 0},%>
<%	{"label":"Recurring", "color":"#DC3912", "value": 0},    %>
<%	{"label":"Life", "color":"#FF9900", "value": 0},         %>
<%	{"label":"Other", "color":"#02D1CE", "value": 0},        %>
<%	{"label":"Special", "color":"#990099", "value": 0},      %>
<%  {"label":"Variable", "color":"#109618", "value": 0}]     %>

<% table_data = IncomeStatement.monthly_view(@user.id) %>
<% table_data.each_with_index do |m, i| %>

    <% donut_data.each do |expense| %>
      <% case expense["label"] %>
      <% when "Discretionary" %>
        <% expense["value"] = m[i]["Discretionary"] %>
      <% when "Recurring" %>
        <% expense["value"] = m[i]["Recurring"] %>
      <% when "Life" %>
        <% expense["value"] = m[i]["Life"] %>
      <% when "Other" %>
        <% expense["value"] = m[i]["Other"] %>
      <% when "Special" %>
        <% expense["value"] = m[i]["Special"] %>
      <% when "Variable" %>
        <% expense["value"] = m[i]["Variable"] %>
      <% end %>
    <% end %>
    <%= binding.pry %>
  <% end %>

app/views/graph/index.html.erb
<%= link_to "checking", graph_data_path, method: :post, remote: true %>

<div id="chart"></div>

<div id="monthly"></div>
<button onClick="changeData()">Change Data</button>
<script>

var salesData=[
	{label:"Discretionary", color:"#3366CC", value: 523},
	{label:"Recurring", color:"#DC3912", value: 2422},
	{label:"Life", color:"#FF9900", value: 1200},
	{label:"Other", color:"#02D1CE", value: 203},
	{label:"Special", color:"#990099", value: 337},
  {label:"Variable", color:"#109618", value: 548}
];


var svg = d3.select("body").append("svg").attr("width",700).attr("height",300);

svg.append("g").attr("id","salesDonut");

Donut3D.draw("salesDonut", randomData(), 150, 150, 130, 100, 30, 0.4);

function changeData(){
	Donut3D.transition("salesDonut", randomData(), 130, 100, 30, 0.4);
}

function randomData(){
	return salesData.map(function(d){
		return {label:d.label, value:d.value, color:d.color};});
}
</script>