config/routes.rb
Rails.application.routes.draw do
  resources :goals
  root 'home#index'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'create'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, except: [:index, :new, :create] do
    resources :transactions, only: [:index, :show, :edit, :update]
    resources :accounts
    resources :budgets, except: [:index]
    resources :goals
  end
  
  # Clean up on these next... 
  post '/users/piechart', to: 'users#piechart'
  post '/users/linegraph', to: 'users#linegraph'

  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
  post 'graph/data', to: 'graph#data'

  get '/users/data', :defaults => { :format => 'json' }

end

# Cleaned
  # get '/update/:id', to: 'users#edit', as: 'edit'
  # patch '/update/:id', to: 'users#update', as: 'user_update'
  # post 'accounts/create', to: 'accounts#create'
  # patch '/update_accounts', to: 'plaidapi#update_accounts'

app/views/layouts/_header.html.erb
<header id="header">
            <!--logo start-->
            <div class="brand">
                <% @user = User.find(session[:user_id])%>
                <span><%= link_to image_tag("Benjamin-Logo-no-pad.png"), user_path(@user), class: "logo" %></span>
            </div>
            <!--logo end-->

            <div class="toggle-navigation toggle-left">
                <button type="button" class="btn btn-default" id="toggle-left" data-toggle="tooltip" data-placement="right" title="Toggle Navigation">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="user-nav">
                <ul>
                        
                    <li class="dropdown settings">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"></a>
                    </li>
                      

                    <li class="dropdown settings">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                       <%= @user.email %> <i class="fa fa-angle-down"></i>
                    </a>
                        <ul class="dropdown-menu animated fadeInDown">
                            <li>
                            <%= link_to edit_user_path(@user)  do %>
                                <i class="fa fa-user"></i>  Profile
                            <% end %>
                            </li>
                            <li>
                            <%= link_to logout_path(@user) do %>
                                <i class="fa fa-power-off"></i>  Logout
                            <% end %>
                            </li>
                        </ul>
                    <li>
                        
                    </li>
                </ul>
            </div>
        </header>

app/views/layouts/_sidebar.html.erb
<!--sidebar left start-->
<nav class="sidebar sidebar-left">
    <ul class="nav nav-pills nav-stacked">
        <center>
            <h5 class="sidebar-header">Navigation</h5>
    
        </center>

        <li class="nav-dropdown">
           <%= link_to new_user_account_path(@user) do %>
           <i class="fa fa-usd"></i> Add an account!
           <% end %>
        </li>

        <li class="nav-dropdown" id="new-goal">
            <%= link_to new_user_account_path(@user) do %>
            <i class="fa fa-usd"></i>Add a goal
            <% end %>
        </li>

        <li class="nav-dropdown">
            <%= link_to user_path(@user) do %>
            <i class="fa fa-television"></i>Dashboard
            <% end %>
        </li>

        <li class="nav-dropdown">
            <%= link_to edit_user_path(@user) do %>
            <i class="fa fa-table"></i> Profile
            <% end %>
        </li>

       <li class="nav-dropdown">
           <%= link_to goals_path(@user) do %>
           <i class="fa fa-usd"></i> Goals
           <% end %>
        </li>

        <li class="nav-dropdown">
           <%= link_to user_transactions_path(@user) do %>
           <i class="fa fa-usd"></i> Transactions
           <% end %>
        </li>


    </ul>
</nav>

<div class="modal fade" id="goalModel" tabindex="-1" role="dialog" aria-labelledby="budetModelLabel">
  
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-budget" id="add-budget">Goal</h4>
        <p>What would you like to purchase?</p>
      </div>
      <div class="modal-body">
        <%= form_for [@user, Goal.new] do |f| %>

        <label>Product Search</label>
        <%= f.text_field :name, placeholder: 'product to purchase' %>

        <button id="search-btn" type="button" class="btn btn-success"></span>Search</button>

      </div>

      <div id="watch-picture" style="padding:0px;" >
        <%= image_tag "Amazon.png" %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Save Goal", class: 'btn btn-success', id: 'goal_submit' %>
        <% end %>
      </div>

    </div>
  </div>
</div>

<script>

  $("#new-goal").on("click", function(e) {
    e.preventDefault()

    $('#goalModel').modal('toggle')
  })

</script>

   <script>
  $(function(){
    $("#watch-picture").hide();
    $("#search-btn").bind('click', function(evt){
      evt.preventDefault();
      $("#watch-picture").show();
    })
  })
  </script>
<!--sidebar left end-->

app/views/layouts/_tiles_top.html.erb
<!--tiles start-->
<div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="dashboard-tile detail tile-red">
                            <div class="content">
                                <h1 class="total-debt-box"><%= number_to_currency(@user.total_debt, {precision: 0, negative_format: "(%u%n)"}) %></h1>
                                <p>Total Debt</p>
                            </div>
                            <div class="icon"><i class="fa fa-minus-square-o"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="dashboard-tile detail tile-turquoise">
                            <div class="content">
                                <h1 class="total-cash-box"><%= number_to_currency(@user.total_cash, {precision: 0, negative_format: "(%u%n)"}) %></h1>
                                <p>Total Cash</p>
                            </div>
                            <div class="icon"><i class="fa fa-dollar"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="dashboard-tile detail tile-blue">
                            <div class="content">
                                <h1 class="weekly-budget-box"><%= number_to_currency(@user.weekly_budget, {precision: 0, negative_format: "(%u%n)"}) %></h1>
                                <p>Weekly Spending</p>
                            </div>
                            <div class="icon"><i class="fa fa-line-chart"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="dashboard-tile detail tile-purple">
                            <div class="content">
                                <h1 class="monthly-budget-box"><%= number_to_currency(@user.monthly_budget, {precision: 0, negative_format: "(%u%n)"}) %></h1>
                                <p> Monthly Spending</p>
                            </div>
                            <div class="icon"><i class="fa fa-area-chart"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <!--tiles end-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<head>
  <title>Benjamin</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SpaceLab</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
  <% end %>

<%= yield %>

</body>
</html>